aosp: skip bionic futex path on hermetic builds
ABSL_INTERNAL_HAVE_FUTEX for Android was being guarded only by checking
for __BIONIC__, so ABSL_INTERNAL_HAVE_FUTEX was being defined for
hermetic builds.

ABSL_INTERNAL_HAVE_FUTEX was enabling a block with platform code that calls
the futex() syscall, causing build issues:

  third_party/abseil-cpp/absl/synchronization/internal/futex.h:
    error: use of undeclared identifier '__NR_futex'
    error: use of undeclared identifier 'FUTEX_WAKE'

This fix ensures that ABSL_INTERNAL_HAVE_FUTEX is only defined for
non-hermetic builds for Android.

Bug: 505627880