posix: check availability of futimes on android
futimes() was added in android API level 26, only define it for older
api versions.

Adds a pragma to ignore the Wunguarded-availability check as it's
currently done in //base/files/file_posix.cc.

Fixes:
 error: 'futimes' is only available on Android 26 or
   newer [-Werror,-Wunguarded-availability]

Bug: 495203133