aosp: suppress sometimes-uninitialized warnings
Suppress warnings when values are used when uninitialized, usually when
"default:" paths are taken in switch statements, e.g.:

third_party/crashpad/crashpad/minidump/minidump_system_info_writer.cc:
   error: variable 'operating_system' is used uninitialized whenever
          switch default is taken [-Werror,-Wsometimes-uninitialized]

For this specific example the warning happens because the migration of
NOTREACHED to be [[noreturn]] is not completed in copied_base and the
default path doesn't end execution before reaching code that uses
operating_system.

Bug: 495203133